### ISSUE TITLE
Full buggy and many useless functions

### ISSUE THREAD

**Issue by aloisberngardt** [mashed-potatoes/USBTrojan#2]
Программа запускается и тут же вылетает. Даже обработка исключений не имплементирована, зато куча ненужных функций, типа узнать CPU или видеокарту. Класс HWID можно выкинуть сразу.
Вот это тоже надо бы поменять:

        public static bool IsSupported(DriveInfo drive) => drive.AvailableFreeSpace > 1024 && drive.IsReady
            && (drive.DriveType == DriveType.Removable || drive.DriveType == DriveType.Network)
            && (drive.DriveFormat == "FAT32" || drive.DriveFormat == "NTFS");

на это

        public static bool IsSupported(DriveInfo drive) => drive.AvailableFreeSpace > 1024 && drive.IsReady
            && (drive.DriveType == DriveType.Removable || drive.DriveType == DriveType.Network)
            && (drive.DriveFormat == "FAT32" || drive.DriveFormat == "NTFS" || drive.DriveFormat == "ExFat");

В остальном код рабочий. Но такая программа должна работать молча, а не выдавать ошибки на каждом шагу. Лучше пусть будет поменьше фунцкий, но те, что есть, должны работать без ошибок. Но ваша программа, вам решать.

**Comment by mashed-potatoes** [comment]
> Программа запускается и тут же вылетает.

Это лучшее описание ошибки. Как я могу чем-то помочь?

---

> Класс HWID можно выкинуть сразу.

Я считаю, что он нужен.

---

> В остальном код рабочий. Но такая программа должна работать молча, а не выдавать ошибки на каждом шагу.

Сейчас я покажу магию: заходим в Свойства → Тип выходных данных → Приложение Windows

---

Есть желание что-то улучшить/изменить? Есть волшебная кнопка: [Fork!](https://github.com/mashed-potatoes/USBTrojan/fork). Я без вопросов приму PR, если он будет полезный.

Ну и самое главное - это не конечный продукт. Никто не гарантирует корректную работу. USBTrojan был сделан за один вечер от скуки.

**Comment by aloisberngardt** [comment]
Извините за немного резкую критику. Я уже подправил программу под свои нужды. Вам в любом случае большое спасибо за код.

"Сейчас я покажу магию: заходим в Свойства → Тип выходных данных → Приложение Windows"
Тут речь не об этом, а о том, что многие исключения не были отловлены.
